### ISSUE TITLE
gTranslate does not work again

### ISSUE THREAD

**Issue by pedro22** [bpierre/gtranslate#49] opened 2015-10-03 23:20 UTC
gTranslate work for a while and is locked, you must enter the code to work again. User DDRPTP on page opinion, he wrote: "gtranslate not working properly, translate API has changed.
We Need to go to this website:http://translate.google.com/translate_a/t?client=gtranslate&amp;sl=
Enter the code gtranslate resume normal operation."

Source: https://addons.mozilla.org/pl/firefox/addon/gtranslate/reviews/

Maybe this time will be repaired gTranslate to work in the private mode.

Thanks.

**Comment by mote0230** [comment] 2015-10-05 14:10
Can't seem to reproduce on my branch, private mode is also fixed there, now we just have to wait on @bpierre to merge and publish ;) Aurora (ff dev editino) is on v43 now so the bug fixed in 9f17b44 is also in effect there, breaking all text replacements, so I hope the new version gets published soon.

**Comment by fluks** [comment] 2015-10-05 14:52
It didn't work on my browser either for a while, maybe for a day or two, the master branch. Works now again.

**Comment by mote0230** [comment] 2015-10-05 17:32
I noticed I got 'banned' too for a day, but I thought it was because i had done too many translate calls too quickly.
I added the token google uses in b7c7c49 , maybe this will help resist future banwaves

**Comment by pedro22** [comment] 2015-10-05 18:25
I do not understand, what I do about it now, compile? 

I'm not a programmer - I do not know on that.

**Comment by pedro22** [comment] 2015-10-09 00:35
An interesting thing that again no problems running a version 0.9.1 - yes, the same who previously display a "Service Unavailable"

**Comment by bpierre** [comment] 2015-10-15 11:36
Can’t reproduce either, please try [with the latest version](https://addons.mozilla.org/en-US/firefox/addon/gtranslate/versions/?page=1#version-0.12.0), and reopen if the issue persists.

**Closed by bpierre** 2015-10-15 11:36 UTC

**Comment by pedro22** [comment] 2015-10-16 09:43
Unfortunately, the problem persists gTranslate Version 0.12.0 and Firefox 41.0.2 - the same situation as <a href="https://github.com/bpierre/gtranslate/issues/38#issuecomment-139210251">here</a> and post below - you can reproduce it as written <a href="https://github.com/bpierre/gtranslate/issues/38#issuecomment-139529432">Mote0230</a>

Win XP SP3

**Comment by bpierre** [comment] 2015-10-16 09:51
OK, I am reopening #38 then.
