### ISSUE TITLE
Documentation for Keyboard Shortcut

### ISSUE THREAD

**Issue by hal-gh** [bpierre/gtranslate#19] opened 2014-01-17 14:58 UTC
Hi there
Thanks for producing this extension - it really is one of the best!

I extensively use this extension by highlighting foreign text in a page and using the CTRL+SHIFT+L keyboard extension to open the gTranslate dialog. However, looking at the homepage on mozilla and the readme here, I don't actually know how I ever found this out, because I can't find it mentioned anywhere.

Would you mind documenting what the official shortcut is or how a user may configure one?

Thank you in advance

**Comment by mote0230** [comment] 2015-09-13 18:56
I tried installing the old version and using your shortcut, but it did not work. I couldn't see anything in the source code either, so I think you might be using another addon to do this, maybe keyconfig addon.
Otherwise this is a duplicate of #2

**Closed by mote0230** 2015-09-13 18:56 UTC

**Comment by hal-gh** [comment] 2015-09-13 20:01
The CTRL+SHIFT+L shortcut still works on my Ubuntu system, Firefox 40.0.3. I've no idea why - I don't have keyconfig or other extension installed.  The same shortcut doesn't work on my MacbookPro using the same FF version, though.

**Comment by mote0230** [comment] 2015-09-13 20:39
That's interesting. I quickly set up an ubuntu VM but still no luck for me. Are you using the latest version of the extension? When can you use the shortcut, for example just after selecting text, and then it right clicks for you and opens the right click translation submenu? I did a quick search in mozilla's dev guide but couldn't find how to open the context menu from inside an extension.
Maybe we can find something interesting in your prefs.js file? http://kb.mozillazine.org/Prefs.js_file

**Comment by hal-gh** [comment] 2015-09-13 21:07
My apologies, I have just realised I had Fast Translate installed too, and it is this which uses the CTRL+SHIFT+L shortcut. Hence, this ticket was raised in error.

**Comment by mote0230** [comment] 2015-09-13 21:09
No problem, glad this mystery got solved :D
