### ISSUE TITLE
Please update for FireFox Quantum

### ISSUE THREAD

**Issue by sergeos** [bpierre/gtranslate#83] opened 2017-12-03 19:26 UTC
Now **gTranslate** is not available for newest version of Firefox.
Please, if possible fix the error.
Many peoples ask about it in reviews:
[https://addons.mozilla.org/ru/firefox/addon/gtranslate/reviews/](url)

**Comment by PerfectSlayer** [comment] 2017-12-04 17:41
Hi @sergeos 
This issue is a duplicate of #66.
Thanks!

**Closed by PerfectSlayer** 2017-12-04 17:41 UTC
